name = "project-dashboard"
compatibility_date = "2026-04-26"
pages_build_output_dir = "client/dist"

[[d1_databases]]
binding = "DB"
database_name = "project-dashboard"
database_id = "c3ffa46a-16d6-44b4-be04-f6d85ec8fcff"
